package StockManagement.ObjectModel.ValueObject;
// Generated Aug 10, 2017 10:15:42 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable 
{


     private int cltCode;
     private String cltName;
     private String cltEmail;
     private String cltTitle;
     private String cltMobile;
     private boolean sendMessage;
     private boolean sendCatalog;
     private Date cltCreationDate;

    public Client() 
    {
    }

	
    public Client(int cltCode, boolean sendMessage, boolean sendCatalog, Date cltCreationDate) 
    {
        this.cltCode = cltCode;
        this.sendMessage = sendMessage;
        this.sendCatalog = sendCatalog;
        this.cltCreationDate = cltCreationDate;
    }
    
    public Client(int cltCode, String cltTitle, String cltName, String cltMobile, String cltEmail, boolean sendMessage, boolean sendCatalog, Date cltCreationDate) 
    {
       this.cltCode = cltCode;
       this.cltTitle = cltTitle;
       this.cltName = cltName;
       this.cltMobile = cltMobile;
       this.cltEmail = cltEmail;
       this.sendMessage = sendMessage;
       this.sendCatalog = sendCatalog;
       this.cltCreationDate = cltCreationDate;
    }
   
    public int getCltCode() 
    {
        return this.cltCode;
    }
    
    public void setCltCode(int cltCode) 
    {
        this.cltCode = cltCode;
    }
    
    public String getCltTitle() 
    {
        return this.cltTitle;
    }
    
    public void setCltTitle(String cltTitle) 
    {
        this.cltTitle = cltTitle;
    }
    
    public String getCltName() 
    {
        return this.cltName;
    }
    
    public void setCltName(String cltName) 
    {
        this.cltName = cltName;
    }
    
    public String getCltMobile() 
    {
        return this.cltMobile;
    }
    
    public void setCltMobile(String cltMobile) 
    {
        this.cltMobile = cltMobile;
    }
    
    public String getCltEmail() 
    {
        return this.cltEmail;
    }
    
    public void setCltEmail(String cltEmail) 
    {
        this.cltEmail = cltEmail;
    }
    
    public boolean isSendMessage() 
    {
        return this.sendMessage;
    }
    
    public void setSendMessage(boolean sendMessage) 
    {
        this.sendMessage = sendMessage;
    }
    
    public boolean isSendCatalog() 
    {
        return this.sendCatalog;
    }
    
    public void setSendCatalog(boolean sendCatalog) 
    {
        this.sendCatalog = sendCatalog;
    }
    
    public Date getCltCreationDate() 
    {
        return this.cltCreationDate;
    }
    
    public void setCltCreationDate(Date cltCreationDate) 
    {
        this.cltCreationDate = cltCreationDate;
    }
}