package StockManagement.ObjectModel.ValueObject;
// Generated Aug 10, 2017 10:15:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType  implements java.io.Serializable {


     private Integer trCode;
     private String source;
     private String destination;
     private Set orders = new HashSet(0);

    public TransactionType() {
    }

	
    public TransactionType(String source, String destination) {
        this.source = source;
        this.destination = destination;
    }
    public TransactionType(String source, String destination, Set orders) {
       this.source = source;
       this.destination = destination;
       this.orders = orders;
    }
   
    public Integer getTrCode() {
        return this.trCode;
    }
    
    public void setTrCode(Integer trCode) {
        this.trCode = trCode;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


