package StockManagement.ObjectModel.ValueObject;
// Generated Aug 10, 2017 10:15:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Action generated by hbm2java
 */
public class Action  implements java.io.Serializable {


     private Integer actCode;
     private String actName;
     private String actDescription;
     private Set roleActions = new HashSet(0);

    public Action() {
    }

	
    public Action(String actName) {
        this.actName = actName;
    }
    public Action(String actName, String actDescription, Set roleActions) {
       this.actName = actName;
       this.actDescription = actDescription;
       this.roleActions = roleActions;
    }
   
    public Integer getActCode() {
        return this.actCode;
    }
    
    public void setActCode(Integer actCode) {
        this.actCode = actCode;
    }
    public String getActName() {
        return this.actName;
    }
    
    public void setActName(String actName) {
        this.actName = actName;
    }
    public String getActDescription() {
        return this.actDescription;
    }
    
    public void setActDescription(String actDescription) {
        this.actDescription = actDescription;
    }
    public Set getRoleActions() {
        return this.roleActions;
    }
    
    public void setRoleActions(Set roleActions) {
        this.roleActions = roleActions;
    }




}


