package StockManagement.ObjectModel.ValueObject;
// Generated Aug 10, 2017 10:15:42 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private Integer brdCode;
     private String brdName;
     private Date brdCreationDate;
     private boolean brdStatus;
     private Set products = new HashSet(0);

    public Brand() {
    }

	
    public Brand(Date brdCreationDate, boolean brdStatus) {
        this.brdCreationDate = brdCreationDate;
        this.brdStatus = brdStatus;
    }
    public Brand(String brdName, Date brdCreationDate, boolean brdStatus, Set products) {
       this.brdName = brdName;
       this.brdCreationDate = brdCreationDate;
       this.brdStatus = brdStatus;
       this.products = products;
    }
   
    public Integer getBrdCode() {
        return this.brdCode;
    }
    
    public void setBrdCode(Integer brdCode) {
        this.brdCode = brdCode;
    }
    public String getBrdName() {
        return this.brdName;
    }
    
    public void setBrdName(String brdName) {
        this.brdName = brdName;
    }
    public Date getBrdCreationDate() {
        return this.brdCreationDate;
    }
    
    public void setBrdCreationDate(Date brdCreationDate) {
        this.brdCreationDate = brdCreationDate;
    }
    public boolean isBrdStatus() {
        return this.brdStatus;
    }
    
    public void setBrdStatus(boolean brdStatus) {
        this.brdStatus = brdStatus;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


