package StockManagement.ObjectModel.ValueObject;
// Generated Aug 10, 2017 10:15:42 AM by Hibernate Tools 4.3.1



/**
 * RoleAction generated by hbm2java
 */
public class RoleAction  implements java.io.Serializable {


     private Integer roActionCode;
     private Action action;
     private Role role;

    public RoleAction() {
    }

    public RoleAction(Action action, Role role) {
       this.action = action;
       this.role = role;
    }
   
    public Integer getRoActionCode() {
        return this.roActionCode;
    }
    
    public void setRoActionCode(Integer roActionCode) {
        this.roActionCode = roActionCode;
    }
    public Action getAction() {
        return this.action;
    }
    
    public void setAction(Action action) {
        this.action = action;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }




}


