package StockManagement.ObjectModel.ValueObject;
// Generated Aug 10, 2017 10:15:42 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */

public class Company  implements java.io.Serializable {


     private Integer compCode;
     private String compName;
     private String compDesc;
     private Date compCreationDate;
     private Integer compStatus;
     private Set stocks = new HashSet(0);
     private Set branches = new HashSet(0);
     private Set orders = new HashSet(0);

    public Company() {
    }

    public Company(String compName, String compDesc, Date compCreationDate, Integer compStatus, Set stocks, Set branches, Set orders) {
       this.compName = compName;
       this.compDesc = compDesc;
       this.compCreationDate = compCreationDate;
       this.compStatus = compStatus;
       this.stocks = stocks;
       this.branches = branches;
       this.orders = orders;
    }
   
    public Integer getCompCode() {
        return this.compCode;
    }
    
    public void setCompCode(Integer compCode) {
        this.compCode = compCode;
    }
    public String getCompName() {
        return this.compName;
    }
    
    public void setCompName(String compName) {
        this.compName = compName;
    }
    public String getCompDesc() {
        return this.compDesc;
    }
    
    public void setCompDesc(String compDesc) {
        this.compDesc = compDesc;
    }
    public Date getCompCreationDate() {
        return this.compCreationDate;
    }
    
    public void setCompCreationDate(Date compCreationDate) {
        this.compCreationDate = compCreationDate;
    }
    public Integer getCompStatus() {
        return this.compStatus;
    }
    
    public void setCompStatus(Integer compStatus) {
        this.compStatus = compStatus;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }
    public Set getBranches() {
        return this.branches;
    }
    
    public void setBranches(Set branches) {
        this.branches = branches;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


